ARG PYTHON_VERSION=3.8.10

FROM python:${PYTHON_VERSION}

ARG SOURCE_ID
ARG OLD_ORIGIN_USER
ARG OLD_ORIGIN_API
ARG OLD_ORIGIN_TOKEN
ARG ORIGIN_USER
ARG ORIGIN_API
ARG ORIGIN_TOKEN

ENV SOURCE_ID=${SOURCE_ID}
ENV OLD_ORIGIN_USER=${OLD_ORIGIN_USER}
ENV OLD_ORIGIN_API=${OLD_ORIGIN_API}
ENV OLD_ORIGIN_TOKEN=${OLD_ORIGIN_TOKEN}
ENV ORIGIN_USER=${ORIGIN_USER}
ENV ORIGIN_API=${ORIGIN_API}
ENV ORIGIN_TOKEN=${ORIGIN_TOKEN}

WORKDIR /app/
COPY *.py /app/ 

RUN python3 -m pip install --upgrade pip && \
pip3 install colorama requests urllib3 chardet

